#!/run/current-system/sw/bin/bash

LOCK_FILE_CAL="$HOME/.cache/eww-calendar_info.lock"
LOCK_FILE_POWERMENU="$HOME/.cache/eww-powermenu.lock"

calendar_info() {
    run() {
        eww open calendar_info
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_CAL" ]]; then
        touch "$LOCK_FILE_CAL"
        run && echo "ok good!"
    else
        eww close calendar_info
        rm "$LOCK_FILE_CAL" && echo "closed"
    fi
}

powermenu() {
    run() {
        eww open power_menu
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_POWERMENU" ]]; then
        eww close notification_tray power_menu todo_list
        touch "$LOCK_FILE_POWERMENU"
        run && echo "ok good!"
    else
        eww close power_menu
        rm "$LOCK_FILE_POWERMENU" && echo "closed"
    fi
}

if [ "$1" = "--calendar_info" ]; then
    calendar_info
elif [ "$1" = "--powermenu" ]; then
    powermenu
fi
