#!/run/current-system/sw/bin/bash

LOCK_FILE_CAL="$HOME/.cache/eww-calendar_info.lock"
LOCK_FILE_POWERMENU="$HOME/.cache/eww-powermenu.lock"

rm "$LOCK_FILE_CAL" && rm "$LOCK_FILE_POWERMENU"

if [[ "$1" == "--shutdown" ]]; then
    systemctl poweroff
elif [[ "$1" == "--restart" ]]; then
    systemctl reboot
elif [[ "$1" == "--logout" ]]; then
    hyprctl dispatch exit
elif [[ "$1" == "--sleep" ]]; then
    systemctl suspend
fi

rm "$LOCK_FILE_CAL" && rm "$LOCK_FILE_POWERMENU"
