#!/run/current-system/sw/bin/bash

TODO_FILE=$HOME/.cache/eww-todo-file

if [[ ! -f "$TODO_FILE" ]]; then
    touch $TODO_FILE
fi

get() {
    cat $TODO_FILE | sed 's/^.*/"value":"&"/' | cat -n | sed 's/\([0-9]\+\)/"id":"&",/' | sed 's/^.*/{&},/' | sed '1i[' | sed '$s/\(.*\),/\1\n]/' | jq
}

count() {
    grep -cE ".*" "$TODO_FILE"
}

update_tasks() {
    eww update todo_tasks="$(get)"
    eww update todo_count="$(count)"
}

add() {
    echo "$1" >> "$TODO_FILE"
    update_tasks
}

remove() {
    sed -i "${1}d" "$TODO_FILE"
    update_tasks
}

move() {
    ADDR=$1
    if [[ $2 == "up" ]]; then
        ADDR=$((ADDR - 1))
    fi

    sed -i -n "${ADDR}{h;n;G};p" $TODO_FILE
    update_tasks
}

if [[ "$1" == "--get" ]]; then
    get
elif [[ "$1" == "--add" ]]; then
    add $2
elif [[ "$1" == "--remove" ]]; then
    remove $2
elif [[ "$1" == "--count" ]]; then
    count
elif [[ "$1" == "--move" ]]; then
    move $2 $3
fi
